### ISSUE TITLE
Still relevant or are there newer solutions?

### ISSUE THREAD

**Issue by RAbraham** [kentonv/home-container#4]
Hi Kenton,

I was wondering if you still use this setup or have moved on to newer solutions or can recommend newer solutions which provide the same isolation?

btw, a big fan of Sandstorm here.

**Comment by kentonv** [comment]
I still use this. At some point I want to update it to use user namespaces since I believe Chrome is compatible with that now. I haven't really looked at other alternatives in this space; there could very well be some good ones by now.

(Closing because there's no action item here, but happy to answer questions.)
